Add internal containership and documentation
relativitydev/containership pull request #1
Opened 2021-05-20 19:48 UTC by lenardchristopher

This PR adds the containership v1 code and common open source documentation.

Highlights
- Tests were removed because they are too specific to Relativity
- CONTRIBUTING.md
- RELEASE_PROCESS.md
- README.md with warning
> **NOTE: This version only supports promotion to Azure container registries and using Palo Alto's Prisma for vulnerability scanning. A new, cloud agnostic, version is in development. It will work with any OCI compliant container registry and support a variety of promotion gates.**

Nothing about this PR is set in stone. It is intended to be a launching point during v2 development.

2021-05-20 20:16 UTC, coreywagehoft requested changes
Could we add a CODEOWNERS file and assign appropriate members of Relativity to this?

2021-05-20 20:17 UTC, lenardchristopher commented on .github/workflows/go-release.yml
> +        run: echo $(ls /home/runner/work/_temp/_github_home)
Ah good call. I'll just remove it for now.

2021-05-24 20:26 UTC, Tomalong approved these changes

2021-05-24 20:29 UTC, justinbanks approved these changes

2021-05-24 20:41 UTC, coreywagehoft approved these changes

2021-05-24 22:20 UTC, merged